// AUTO-GENERATED by scripts/generate-sounds-manifest.mjs — DO NOT EDIT.
// Regenerated automatically whenever `vite` (dev/build/preview) starts, or
// manually with `npm run refresh-sounds`. Add an MP3 to public/ and rerun.

/** Root-relative URLs of every MP3 file directly inside public/. */
export const SOUND_FILES: readonly string[] = [
  '/brown_noise.mp3',
  '/crackling_fireplace.mp3',
  '/forest_ambience_1.mp3',
  '/forest_ambience_2.mp3',
  '/relaxing_rain.mp3',
  '/river_sounds.mp3',
  '/soothing_ocean_waves.mp3',
];
